.PHONY: all
.PHONY: install
.PHONY: clean

ISP_PREFIX ?= /opt/isp/

all:
	stack build --allow-different-user --ghc-options="-Wall"

install:
	stack install --local-bin-path=$(ISP_PREFIX)/bin/ --ghc-options="-Wall"

clean:
	stack clean
