#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get update

apt-get install -y \
        wget

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $SCRIPT_DIR > /dev/null

rm -rf ./stack.html
wget -O ./stack.html https://get.haskellstack.org/

sha512sum -c <<< "0c816cd6b4a3f502f049c79790e3d4d9fb12237b7ed5b29d38def41119b6fd5a001ead379bd7ef85b9fc71835a4b94bfb73eea62b1f4180d58b27a69a0ad4b61  stack.html"

bash stack.html -f
rm -rf ./stack.html
