#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get update

apt-get install -y \
        wget

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $SCRIPT_DIR > /dev/null

rm -rf ./stack.html
wget -O ./stack.html https://get.haskellstack.org/

sha512sum -c <<< "4ec9c36549bfe39b00b4bcbc41f2e2b92b56c83774a50e3003d085e0750019bf9efb6817c9ab45e69e65df3ade027962c7ace1406ca05cde77c096e34eee865c  stack.html"

bash stack.html -f
rm -rf ./stack.html
